### ISSUE TITLE
autoreconf -i fails

### ISSUE THREAD

**Issue by Akretsch** [engine-corner/engine-chil#11]
`autoreconf -i` outputs:
< lot of lines about libtoolize>
```
configure.ac:18: error: possibly undefined macro: AC_MSG_FAILURE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

But if you drop the lines below from configure.ac the `autoreconf -i;./configure;make` sequence works:
```
AX_CHECK_OPENSSL(
  [have_openssl=yes],
  [AC_MSG_FAILURE([could not locate OpenSSL])]
)
```
Tested at Debian GNU/Linux 9 with OpenSSL 1.1.0j  20 Nov 2018.

**Comment by levitte** [comment]
Weird. That is a [documented autoconf macro](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Printing-Messages.html#index-AC_005fMSG_005fFAILURE-1231)

**Comment by sctemme** [comment]
On my Ubuntu system, this macro is part of the _autoconf-archive_ package. I'd expect it to be transparently available on systems that have this package installed, but missing on systems that don't.

**Comment by levitte** [comment]
It turns out that [`AC_MSG_FAILURE` isn't the problem](https://stackoverflow.com/questions/35804500/possibly-undefined-macro-ac-msg-failure), `AX_CHECK_OPENSSL` is, and yes, that requires *autoconf-archive* to be installed.

That requirement is listed in `README.md`...  I'm therefore closing this issue.

**Comment by Akretsch** [comment]
The error message was misleading, thanks for help and clarification.
