### ISSUE TITLE
Should we bundle ax_check_openssl.m4?

### ISSUE THREAD

**Issue by sctemme** [engine-corner/engine-chil#9]
Absence of this macro file trips me up every time I check out a fresh copy.  Should we bundle it into the repository?  Its license seems benign enough.

**Comment by levitte** [comment]
Is it only me who always `autoreconf -i` directly after checking out something autoconfigurable?

I would prefer *not* to put externally generated files into the engine source...  That's often a maintenance issue (or nightmare, depending on your mood) waiting to happen.
